version: "3.9"

services:
  backend:
    container_name: mess-backend
    build: be
    image: jostrzol/mess-backend
    ports:
      - 4000:4000
    environment:
      MESS_PORT: 4000
      MESS_INCOMING_ORIGIN: http://${PROXY_SERVER_NAME}:${PROXY_PORT}

  frontend:
    container_name: mess-frontend
    build: fe
    image: jostrzol/mess-frontend
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      BACKEND_URL: ${PROXY_SERVER_NAME}:${PROXY_PORT}/api

  proxy:
    container_name: mess-proxy
    depends_on:
      - backend
      - frontend
    build: proxy
    image: jostrzol/mess-proxy
    ports:
      - ${PROXY_PORT}:80

