# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Check backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./be
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install Go tools
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2

    - name: Build
      run: go build -v ./...

    - name: Lint
      run: golangci-lint run -E revive,godot

    - name: Test
      run: go test -v ./...
