# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Check backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

  build:
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
    - name: Build
      run: go build -v ./...
      working-directory: ./be

  lint:
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2

    - name: Lint
      run: golangci-lint run -E revive,godot
      working-directory: ./be

  test:
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
    - name: Test
      run: go test -v ./...
      working-directory: ./be
