name: Publish

on:
  release:
    types: [published]

jobs:
  publish-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./be
            image: jostrzol/mess-backend
          # - context: ./fe
          #   image: jostrzol/mess-frontend
          # - context: ./proxy
          #   image: jostrzol/mess-proxy
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        push: true
        tags: ${{ matrix.image }}:latest
        cache-from: type=registry,ref=${{ matrix.image }}:latest
        cache-to: type=inline
